### ISSUE TITLE
1.0.4 support

### ISSUE THREAD

**Issue by Handri-Kosada** [wolfrage76/windows-plotman#1]
Hi, 

Great job!

Could you update to 1.0.4 support?
I think there is changes in the log date stamp format.

Thanks.

**Comment by wolfrage76** [comment]
1.0.4 was released?  I don't see it available?

**Comment by Handri-Kosada** [comment]
Sorry I was doing the chia 1.0.4beta but in linux and under impression they have the windows beta 1.0.4 also.
they fixed it in plotman development branch. So just wondering if you are catching up with the plotman development branch also.

ps.  I heard they will release 1.0.4 on  Monday 12 April 2021

**Comment by Handri-Kosada** [comment]
it is out and running well with 1.0.4
