### ISSUE TITLE
plotman hang in powershell

### ISSUE THREAD

**Issue by Handri-Kosada** [wolfrage76/windows-plotman#5]
Hi,

my plotman hang / freeze and doesnt respond to Q key or CTRL + C.
How do I gain my plotman back? If I close my powershell, all the chia2 process will be terminated.

Thanks.

ps.

I still can see the plot running from cmd :  
C:\plotman>python plotman.py status
    plot id    k       tmp       dst   wall   phase    tmp     pid   stat    mem   user    sys   io
36a956c6...   32   G:\Temp   G:\Temp   0:20     1:3    93G   16128    RUN   7.9G   0:57   0:02   0s
3aae5e69...   32   G:\Temp   G:\Temp   3:29     2:3   350G   17308    RUN   6.8G   6:55   0:16   0s
e5d6ce9d...   32   G:\Temp   G:\Temp   5:08     3:3   309G   13368    RUN   6.8G   8:20   0:23   0s
f4485de9...   32   G:\Temp   G:\Temp   6:39     3:6   222G   13432    RUN   6.8G   9:38   0:30   0s

**Comment by Handri-Kosada** [comment]
is there any diff if I run it via cmd Vs PowerShell?

**Comment by Handri-Kosada** [comment]
PS C:\plotman> python.exe plotman.py plot
...starting plot loop
g:\logs\2021-04-12-18.43.33.log
Traceback (most recent call last):
  File "C:\plotman\plotman.py", line 95, in <module>
    wait_reason = manager.maybe_start_new_plot(dir_cfg, sched_cfg, plotting_cfg)
  File "C:\plotman\manager.py", line 131, in maybe_start_new_plot
    p = subprocess.Popen(plot_args,
  File "C:\Users\Kosada\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kosada\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by wolfrage76** [comment]
Did you follow the instructions to copy chia.exe to chia2.exe for the time
being?  It's looking for that file currently, until testing is done, so
that it doesn't interfere with other running plots.

--Alan

**Comment by Handri-Kosada** [comment]
yes I did. never mind i will close this, it is working now.
